# Generated by Django 4.2.4 on 2023-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='pictures',
            field=models.ImageField(default='0.jpg', upload_to='coffee/img'),
        ),
    ]
