image: python:3.10

stages:
  - build
  - lint
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the application..."
    - apt-get update && apt-get install -y curl
    - curl -sSL <https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py> | python
    - source $HOME/.poetry/env
    - poetry config virtualenvs.create false
    - poetry install
    - echo "Build completed."

lint:
  stage: lint
  script:
    - poetry run flake8 .
    - poetry run mypy .

test_job:
  stage: test
  services:
    - postgres:latest
  script:
    - echo "Running tests..."
    - poetry run pytest .

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - poetry run python manage.py migrate
    - docker-compose up -d

