name: CI/CD Pipeline

on:
  push:
    branches:
      - features/CI.CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install

      - name: Build the application
        run: echo "Building the application..."

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install

      - name: Run linting
        run: |
          poetry run flake8 .
          poetry run mypy .

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: poetry run pytest .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install

      - name: Deploy the application
        run: |
          poetry run python manage.py migrate
          docker-compose up -d
